### ISSUE TITLE
CS4ZP6 Tester Feedback: Redirection bug

### ISSUE THREAD

**Issue by Behzadkha** [trevorNgo/Measure2.0#146] opened 2021-02-25 15:40 UTC
After closing the view plot. You will be navigated to the Input measurement tab not the original dashboard

Environment:
Windows Desktop,
Browser: Chrome

Steps to reproduce:
Login as instructor, 
Click on VIEW PLOTS
Close the plot and you will be redirected to the INPUT MEASUREMENT tab instead of the main dashboard
![image](https://user-images.githubusercontent.com/24414425/109177497-df775f80-7755-11eb-91ce-6c73af7fec7a.png)

Severity:
LOW

**Comment by trevorNgo** [comment] 2021-02-25 18:16
@michaelkhancode this may be by design now, so we may want to remove this button shortcut.

**Comment by michaelkhancode** [comment] 2021-03-07 22:46
I think removing the button makes the most logical sense.

**Comment by michaelkhancode** [comment] 2021-03-08 03:20
resolved in: https://github.com/trevorNgo/Measure2.0/pull/246

**Closed by michaelkhancode** 2021-03-08 03:20 UTC
Labels: bug, tester
